#!/usr/bin/env python3
"""Legacy spatial-figure helper from the earlier appendix workflow.

The current paper figures are generated by make_spatial_cache.py,
make_figures.py, and make_scatter.py. Keep this script only for ad-hoc
comparisons against the older full grid-scatter products.

    conda run -n s2s-hind python paper_v2/scripts/make_spatial_figures.py
"""
from __future__ import annotations

import os

import cartopy.crs as ccrs
import cartopy.feature as cfeature
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats

ROOT = "/home/raj.ayush/s2s/s2s_anlysis/final_paper/outputs/s2s_paper_outputs"
OUT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "figs"))
os.makedirs(OUT, exist_ok=True)

GRID = {
    "jfm": f"{ROOT}/jfm2026/03_metrics/full_jfm2026_daily_spire/scatter_grid_weekly.csv",
    "jjas": f"{ROOT}/jjas2019/03_metrics/full_jjas2019_common17_fuxi_imd/scatter_grid_weekly.csv",
}
AREA = {
    "jfm": f"{ROOT}/jfm2026/03_metrics/full_jfm2026_daily_spire/scatter_area_weekly.csv",
    "jjas": f"{ROOT}/jjas2019/03_metrics/full_jjas2019_common17_fuxi_imd/scatter_area_weekly.csv",
}

LABEL = {
    "spire": "Spire AI-S2S", "fuxi": "FuXi-S2S", "delysm": "DLESyM",
    "ecmwf": "ECMWF", "ukmo": "UKMO", "ncep": "NCEP", "mme": "MME",
}

plt.rcParams.update({
    "font.family": "serif",
    "font.serif": ["Palatino", "Palatino Linotype", "DejaVu Serif"],
    "mathtext.fontset": "stix",
    "font.size": 9.5,
    "axes.titlesize": 10,
    "axes.titleweight": "bold",
    "figure.dpi": 200,
    "savefig.dpi": 300,
    "savefig.bbox": "tight",
})


def _load_grid(season, variable, week, models):
    df = pd.read_csv(GRID[season], usecols=[
        "variable", "model", "week", "lat", "lon", "init_date",
        "forecast_anomaly", "truth_anomaly"])
    return df[(df["variable"] == variable) & (df["week"] == week)
              & (df["model"].isin(models))]


def _gridcell_acc(df):
    """Per-(lat,lon) Pearson correlation across initializations."""
    out = []
    for (lat, lon), g in df.groupby(["lat", "lon"]):
        if g["forecast_anomaly"].notna().sum() < 5:
            continue
        r = np.corrcoef(g["forecast_anomaly"], g["truth_anomaly"])[0, 1]
        out.append((lat, lon, r))
    return pd.DataFrame(out, columns=["lat", "lon", "acc"])


def fig_spatial_acc_maps():
    """Spatial week-1 TP ACC maps for Spire, ECMWF, MME (JFM 2026)."""
    models = ["spire", "ecmwf", "mme"]
    fig, axes = plt.subplots(1, 3, figsize=(11, 4.2),
                             subplot_kw={"projection": ccrs.PlateCarree()})
    for ax, m in zip(axes, models):
        df = _load_grid("jfm", "tp", 1, [m])
        g = _gridcell_acc(df)
        sc = ax.scatter(g["lon"], g["lat"], c=g["acc"], cmap="RdYlBu",
                        vmin=-0.4, vmax=1.0, s=170, marker="s",
                        transform=ccrs.PlateCarree(), edgecolors="none")
        ax.add_feature(cfeature.COASTLINE, lw=0.6, edgecolor="#333")
        ax.add_feature(cfeature.BORDERS, lw=0.4, edgecolor="#666", linestyle=":")
        ax.set_extent([65, 100, 5, 38], crs=ccrs.PlateCarree())
        ax.set_title(f"{LABEL[m]}", pad=8)
    cbar = fig.colorbar(sc, ax=axes, orientation="horizontal", fraction=0.05,
                        pad=0.1, aspect=40, shrink=0.7)
    cbar.set_label("Local temporal ACC (across initializations)")
    fig.savefig(f"{OUT}/fig_spatial_acc_tp.pdf", bbox_inches="tight")
    plt.close(fig)
    print("wrote fig_spatial_acc_tp.pdf")


def fig_spatial_acc_z500():
    """Spatial week-1 Z500 ACC maps for Spire, ECMWF, MME (JFM 2026)."""
    models = ["spire", "ecmwf", "mme"]
    fig, axes = plt.subplots(1, 3, figsize=(11, 4.2),
                             subplot_kw={"projection": ccrs.PlateCarree()})
    for ax, m in zip(axes, models):
        df = _load_grid("jfm", "z500", 1, [m])
        g = _gridcell_acc(df)
        sc = ax.scatter(g["lon"], g["lat"], c=g["acc"], cmap="RdYlBu",
                        vmin=0.4, vmax=1.0, s=170, marker="s",
                        transform=ccrs.PlateCarree(), edgecolors="none")
        ax.add_feature(cfeature.COASTLINE, lw=0.6, edgecolor="#333")
        ax.add_feature(cfeature.BORDERS, lw=0.4, edgecolor="#666", linestyle=":")
        ax.set_extent([65, 100, 5, 38], crs=ccrs.PlateCarree())
        ax.set_title(f"{LABEL[m]}", pad=8)
    cbar = fig.colorbar(sc, ax=axes, orientation="horizontal", fraction=0.05,
                        pad=0.1, aspect=40, shrink=0.7)
    cbar.set_label("Local temporal ACC (across initializations)")
    fig.savefig(f"{OUT}/fig_spatial_acc_z500.pdf", bbox_inches="tight")
    plt.close(fig)
    print("wrote fig_spatial_acc_z500.pdf")


def fig_scatter_r2():
    """Forecast vs truth anomaly scatter with R^2, pooled over all
    initializations/weeks/grid cells, for the MME (both seasons, TP+Z500)."""
    fig, axes = plt.subplots(2, 2, figsize=(8.0, 7.6))
    panels = [
        (axes[0, 0], "jfm", "tp", "JFM 2026 — Precipitation (MME)", "mm day$^{-1}$ anomaly"),
        (axes[0, 1], "jfm", "z500", "JFM 2026 — Z500 (MME)", "m anomaly"),
        (axes[1, 0], "jjas", "tp", "JJAS 2019 — Precipitation (MME)", "mm day$^{-1}$ anomaly"),
        (axes[1, 1], "jjas", "z500", "JJAS 2019 — Z500 (MME)", "m anomaly"),
    ]
    for ax, season, var, title, axlabel in panels:
        df = pd.read_csv(GRID[season], usecols=[
            "variable", "model", "forecast_anomaly", "truth_anomaly"])
        sub = df[(df["variable"] == var) & (df["model"] == "mme")].dropna()
        if sub.empty:
            ax.set_visible(False)
            continue
        x, y = sub["truth_anomaly"].values, sub["forecast_anomaly"].values
        r2 = stats.pearsonr(x, y)[0] ** 2
        ax.hexbin(x, y, gridsize=45, cmap="Blues", mincnt=1, bins="log")
        lims = [min(x.min(), y.min()), max(x.max(), y.max())]
        ax.plot(lims, lims, color="#D55E00", lw=1.2, ls="--", label="1:1")
        ax.set_xlim(lims)
        ax.set_ylim(lims)
        ax.set_xlabel(f"ERA5/IMD truth anomaly ({axlabel})")
        ax.set_ylabel(f"Forecast anomaly ({axlabel})")
        ax.set_title(f"{title}\n$R^2={r2:.2f}$, $n={len(x):,}$", fontsize=9.5)
        ax.legend(loc="upper left", fontsize=8, frameon=False)
        ax.set_aspect("equal", adjustable="box")
    fig.tight_layout(h_pad=3.0, w_pad=2.5)
    fig.savefig(f"{OUT}/fig_scatter_r2.pdf")
    plt.close(fig)
    print("wrote fig_scatter_r2.pdf")


def main():
    fig_spatial_acc_maps()
    fig_spatial_acc_z500()
    fig_scatter_r2()
    print(f"\nAll spatial figures written to {OUT}")


if __name__ == "__main__":
    main()
