#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
jfm2026/config.py  —  The JFM2026 experiment definition (paths + models).
================================================================================
This is the ONE place JFM2026-specific facts live. To verify a different season,
copy this file, change the dates/paths/models, and run the same driver.

Paths resolved from the current /storage layout (June 2026 reorganisation):
  FuXi    All_Model_Data/fuxi/jfm2026/combined/<init>.nc
  ECMWF   All_Model_Data/ecmwf/jfm2026/{tp,z/500}/<init>_pf.nc
  SPIRE   s2s-forecast-data-prev/spire/spire_hindcast_jfm.zarr   (mean_stddev)
  truth   s2s-forecast-data-prev/era5/daily/era5_daily_{tp,t2m}.nc + z500 GRIB
  clim    benchmark(jfm)/era5_climatology.nc
  masks   s2s-forecast-data-prev/era5/daily/imd_region_masks.nc
================================================================================
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.append(os.path.dirname(HERE))                 # final_analysis/ on path

from core import ExperimentConfig, ModelSpec, GridSpec, Paths, Physics

STORE = "/storage/raj.ayush"
PREV = f"{STORE}/s2s-forecast-data-prev"               # ERA5 truth + SPIRE live here


def region_mask_path(dgrid) -> str:
    """IMD region-mask NetCDF for a given grid spacing.
       1.5° uses the long-validated existing file; other resolutions use the
       masks generated by `python -m core.regions` into final_analysis/masks/."""
    if abs(dgrid - 1.5) < 1e-6:
        return f"{PREV}/era5/daily/imd_region_masks.nc"
    return os.path.join(os.path.dirname(HERE), "masks", f"imd_region_masks_{dgrid:g}deg.nc")


def build_config(dgrid: float = 1.5, fuxi_root: str | None = None,
                 fuxi_members: int | None = None,
                 out_suffix: str | None = None) -> ExperimentConfig:
    """JFM2026 config at a chosen verification resolution.
       dgrid=1.5 -> common/fair grid (default);  dgrid=0.5 -> SPIRE-native grid.

       FuXi can be redirected to a larger ensemble directory without editing code:
           python run_verify.py --fuxi-root /storage/.../fuxi/jfm2026_ens50 \
                                --fuxi-members 50 --out-suffix ens50
       The adapter expects <fuxi_root>/combined/<YYYYMMDD>.nc."""
    fuxi_root = fuxi_root or os.environ.get("FUXI_JFM_ROOT") or f"{STORE}/All_Model_Data/fuxi/jfm2026"
    fuxi_members = int(fuxi_members or os.environ.get("FUXI_JFM_MEMBERS") or 11)
    out_suffix = out_suffix or os.environ.get("S2S_OUT_SUFFIX", "")
    out_name = f"results_{dgrid:g}deg" + (f"_{out_suffix}" if out_suffix else "")

    paths = Paths(
        clim_nc        = f"{STORE}/benchmark(jfm)/era5_climatology.nc",
        region_mask_nc = region_mask_path(dgrid),
        era5_daily_tp  = f"{PREV}/era5/daily/era5_daily_tp.nc",
        era5_daily_t2m = f"{PREV}/era5/daily/era5_daily_t2m.nc",
        era5_z500_grib = f"{PREV}/era5/data/era5_pressure_500hpa.grib",
        soi_shapefile  = f"{STORE}/archive/s2s-forecast-/STATE_BOUNDARY.shp",
    )

    models = [
        ModelSpec(name="SPIRE", adapter="spire_mean_stddev",
                  kwargs={"zarr": f"{PREV}/spire/spire_hindcast_jfm.zarr",
                          "group": "mean_stddev"}),
        ModelSpec(name="FuXi", adapter="fuxi_combined",
                  kwargs={"root": fuxi_root, "members": fuxi_members}),
        ModelSpec(name="ECMWF", adapter="ecmwf_byvar",
                  kwargs={"root": f"{STORE}/All_Model_Data/ecmwf/jfm2026",
                          "ens": "pf"}),
    ]

    return ExperimentConfig(
        season_label="JFM2026",
        init_dates=(
            "2026-01-01", "2026-01-08", "2026-01-15", "2026-01-22", "2026-01-29",
            "2026-02-05", "2026-02-12", "2026-02-19", "2026-02-26",
            "2026-03-05", "2026-03-12", "2026-03-19", "2026-03-26",
        ),
        valid_end="2026-05-10",            # last ERA5 daily-truth date
        valid_end_clim="2026-05-15",
        grid=GridSpec(lat0=38.0, lat1=5.0, lon0=65.0, lon1=100.0, dgrid=dgrid),
        paths=paths,
        physics=Physics(),
        models=models,
        # T2M: SPIRE + FuXi only (both instantaneous). ECMWF forecast temperature
        # is not on disk (analysis-only 2t, empty mx2t/mn2t) -> its adapter returns
        # None for T2M, so it is auto-excluded from the T2M track.
        variables=("TP", "Z500", "T2M"),
        out_dir=os.path.join(HERE, out_name),   # per-resolution/fuxi-ensemble folder
    )


CFG = build_config()
